import Head from 'next/head';
import Image from 'next/image';
import { BsMoonStarsFill } from 'react-icons/bs';

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Aya Ogihara</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <section className='min-h-screen'>
          <nav>
            <h1>Aya Ogihara</h1>
            <ul>
              <li>
                <BsMoonStarsFill />
              </li>
              <li>
                <a href='#'>Resume</a>
              </li>
            </ul>
          </nav>
        </section>
      </main>
    </>
  );
}
